-- 코드를 입력하세요

SELECT DATE_FORMAT(sales_date, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM online_sale
WHERE sales_date BETWEEN '2022-03-01' AND '2022-03-31' 

UNION ALL 

SELECT DATE_FORMAT(sales_date, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM offline_sale 
WHERE sales_date BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY 1, 2, 3