SELECT 
    CONCAT('/home/grep/src/', UG.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM 
    USED_GOODS_FILE UGF
JOIN 
    (SELECT BOARD_ID
     FROM USED_GOODS_BOARD
     ORDER BY VIEWS DESC
     LIMIT 1) UG ON UG.BOARD_ID = UGF.BOARD_ID
ORDER BY 
    UGF.FILE_ID DESC;
